import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  menuBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    elevation: 4,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  scrollContent: {
    paddingHorizontal: 4,
  },
  leftScroll: {
    flex: 1,
  },
  rightScroll: {
    flex: 1,
  },
  menuItem: {
    paddingVertical: 8,
    marginHorizontal: 2,
    borderRadius: 4,
    alignItems: 'center',
  },
  activeMenuItem: {
    backgroundColor: '#e3f2fd',
  },
  menuText: {
    fontSize: 13,
    color: '#333',
    fontWeight: '500',
    textAlign: 'center',
  },
  centerControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  roundButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#dcdcdc',
    justifyContent: 'center',
    alignItems: 'center',
  },
  qButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#2F5C8F',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 8,
  },
  qText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 22,
  },
  quickAccessBar: {
    flexDirection: 'row',
    padding: 8,
    backgroundColor: '#E5F3FC',
    elevation: 2,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  quickAccessContent: {
    paddingHorizontal: 8,
  },
  quickCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#4285f4',
  },
  quickName: {
    color: 'black',
    fontSize: 10,
    textAlign: 'center',
    marginTop: 2,
  },
  quickValue: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  secondaryBar: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    elevation: 2,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  secondaryContent: {
    paddingHorizontal: 8,
  },
  secondaryItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 70,
    borderWidth: 2,
    borderRadius: 8,
    borderColor: '#e0e0e0',
  },
  secondaryText: {
    fontSize: 10,
    color: '#333',
    marginTop: 4,
  },
  titleButton: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    backgroundColor: '#bce0f8',
    justifyContent: 'center',
  },
  titleText: {
    fontSize: 18,
    color: '#333',
    textAlign: 'center',
    fontWeight: '800',
  },
  cancelpageButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#4285f4',
    width: 100,
    justifyContent: "center",
    alignItems: "center"
  },
  cancelpagetext: {
    fontSize: 16,
    color: '#fff',
    textAlign: "center"
  },
  cancelButton: {
    paddingHorizontal: 18,
    justifyContent: 'center',
  },
  cancelText: {
    fontSize: 30,
    color: '#333',
  },
  alignmentModalContainer: {
    backgroundColor: '#fff',
    borderRadius: 30,
    padding: 16,
    width: '70%',
    elevation: 4,
    paddingVertical: 30,
  },
  documentContainer: {
    flex: 1,
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    margin: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  documentArea: {
    minHeight: '100%',
    paddingTop: 16,
    color: '#333',
    lineHeight: 24,
    textAlignVertical: 'top',
    alignSelf: 'flex-start',
    width: '100%',
  },
  boldText: {
    fontWeight: 'bold',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContainer: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 16,
    width: '80%',
    elevation: 4,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
    color: '#333',
  },
  fontSizeInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 4,
    padding: 8,
    marginBottom: 16,
    fontSize: 16,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  modalButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 4,
    marginLeft: 8,
  },
  modalButtonPrimary: {
    backgroundColor: '#4285f4',
  },
  modalButtonText: {
    color: '#333',
  },
  modalButtonPrimaryText: {
    color: '#fff',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
    width: '80%',
  },
  pageSizeOption: {
    paddingVertical: 10,
  },
  pageSizeText: {
    fontSize: 16,
  },
  alignmentOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
  },
  alignmentText: {
    marginLeft: 10,
    fontSize: 16,
    color: '#333',
  },
  rulerContainer: {
    height: 40,
    backgroundColor: '#f0f0f0',
    position: 'relative',
    marginHorizontal: 0,
    marginTop: 5,
    marginBottom: 5,
    justifyContent: 'center',
  },
  rulerScale: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 30,
    marginHorizontal: 10,
  },
  rulerMarkContainer: {
    alignItems: 'center',
    width: 25,
  },
  rulerMark: {
    width: 2,
    height: 15,
    backgroundColor: '#888',
    marginBottom: 2,
  },
  rulerLabel: {
    fontSize: 10,
    color: '#888',
  },
  marginMarker: {
    position: 'absolute',
    top: 0,
    width: 10,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  markerHandle: {
    width: 10,
    height: 30,
    backgroundColor: '#4285f4',
    borderRadius: 5,
  },
  notification: {
    position: 'absolute',
    top: 40,
    left: 20,
    right: 20,
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
  },
  notificationText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
    textAlign: 'center',
  },
  tableContainer: {
    borderWidth: 1,
    borderColor: "#000",
    marginVertical: 10,
    alignSelf: "center",
  },
  tableRow: {
    flexDirection: "row",
  },
  tableCell: {
    borderWidth: 1,
    borderColor: "#000",
    width: 80,
    height: 40,
    padding: 5,
    textAlign: "center",
    padding: 5,
  },


});

export default styles;